#!/usr/bin/env python3
"""
15_customer_dedup_analysis.py — JWM1451-57

Walks `JWM Production Schedule Line` records (and Customer records) and
reports duplicate / near-duplicate customer names so we can present a
dedup proposal to Chris before any merge writes.

Phase 1 = analysis only. NO merges. Writes:
  - logs/15_customer_dedup_proposal.md (human-readable)
  - logs/15_customer_dedup_proposal.json (machine-readable, for a Phase-2 merge script)

Heuristics:
  - case-fold + strip suffixes (Inc, LLC, Corp, Co.) + collapse spaces
  - Levenshtein distance ≤ 2 on the normalised form
  - common-prefix matches (e.g. "Vanderlande" matches "Vanderlande Industries"
    when one is a prefix of the other and the shared prefix is ≥ 6 chars).
"""
from __future__ import annotations

import json
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _frappe import FrappeClient, setup_logging

LOG = setup_logging("./logs", "15_customer_dedup")
HERE = Path(__file__).parent
OUT_MD = HERE / "logs" / "15_customer_dedup_proposal.md"
OUT_JSON = HERE / "logs" / "15_customer_dedup_proposal.json"

SUFFIXES = re.compile(r"\b(inc|incorporated|llc|l\.l\.c\.|corp|corporation|co|company|ltd|limited|the)\b\.?", re.IGNORECASE)
PUNCT = re.compile(r"[.,/&'()\[\]\-_]")
WS = re.compile(r"\s+")


def normalise(s: str) -> str:
    if not s: return ""
    s = s.lower()
    s = PUNCT.sub(" ", s)
    s = SUFFIXES.sub(" ", s)
    s = WS.sub(" ", s).strip()
    return s


def levenshtein(a: str, b: str, cap: int = 3) -> int:
    """Bounded Levenshtein. Returns cap+1 if exceeded — we only care up to `cap`."""
    if a == b: return 0
    if abs(len(a) - len(b)) > cap: return cap + 1
    if not a: return len(b)
    if not b: return len(a)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        curr = [i] + [0] * len(b)
        min_row = curr[0]
        for j, cb in enumerate(b, 1):
            cost = 0 if ca == cb else 1
            curr[j] = min(curr[j-1] + 1, prev[j] + 1, prev[j-1] + cost)
            if curr[j] < min_row: min_row = curr[j]
        if min_row > cap: return cap + 1
        prev = curr
    return prev[-1]


def main():
    fc = FrappeClient.from_env()
    LOG.info("Fetching Customer records…")

    # Pull customer master — single batch up to 2000 rows.
    customers = fc.get_list("Customer", fields=("name", "customer_name"), limit=2000)
    LOG.info("Customer rows: %d", len(customers))

    # Group by normalised name
    buckets: dict[str, list[dict]] = defaultdict(list)
    for c in customers:
        norm = normalise(c.get("customer_name") or c.get("name") or "")
        if norm:
            buckets[norm].append(c)

    exact_dups: list[dict] = []
    for norm, members in buckets.items():
        if len(members) > 1:
            exact_dups.append({
                "normalised": norm,
                "members": [m.get("name") for m in members],
                "count": len(members),
                "kind": "exact_normalised_match",
            })

    # Near-match pairs (Levenshtein ≤ 2 on normalised)
    near: list[dict] = []
    norms = sorted(buckets.keys())
    for i, a in enumerate(norms):
        for b in norms[i+1:]:
            if abs(len(a) - len(b)) > 2: continue
            d = levenshtein(a, b, cap=2)
            if 1 <= d <= 2:
                near.append({
                    "left": a,
                    "right": b,
                    "distance": d,
                    "left_members": [m.get("name") for m in buckets[a]],
                    "right_members": [m.get("name") for m in buckets[b]],
                })

    # Common-prefix (rough acquisition / parent-child)
    prefix: list[dict] = []
    for i, a in enumerate(norms):
        for b in norms[i+1:]:
            if a == b or len(a) < 6 or len(b) < 6: continue
            if b.startswith(a + " ") or a.startswith(b + " "):
                prefix.append({
                    "shorter": a if len(a) < len(b) else b,
                    "longer":  b if len(a) < len(b) else a,
                    "kind": "prefix_match",
                })

    summary = {
        "total_customers": len(customers),
        "distinct_normalised": len(buckets),
        "exact_normalised_collisions": len(exact_dups),
        "near_match_pairs": len(near),
        "prefix_match_pairs": len(prefix),
    }
    LOG.info("Summary: %s", summary)

    OUT_JSON.write_text(json.dumps({
        "summary": summary,
        "exact_dups": exact_dups,
        "near": near,
        "prefix": prefix,
    }, indent=2))

    md = ["# Customer dedup proposal", "",
          f"_Generated by `15_customer_dedup_analysis.py` against `{os.getenv('FRAPPE_BASE_URL', '')}`._",
          "",
          "## Summary",
          ""]
    for k, v in summary.items():
        md.append(f"- **{k.replace('_', ' ').title()}**: {v}")
    md += ["", "## Exact normalised collisions",
           "Same name after stripping suffixes / punct / case. **Almost certainly merge candidates.**", ""]
    for d in sorted(exact_dups, key=lambda x: -x["count"])[:50]:
        md.append(f"- `{d['normalised']}` × {d['count']} — members: " + ", ".join(f"`{m}`" for m in d["members"]))
    if not exact_dups:
        md.append("_(none)_")

    md += ["", "## Near matches (Levenshtein ≤ 2)",
           "Likely typos, acronyms, or punctuation drift. Each pair needs human eyeball.", ""]
    for n in sorted(near, key=lambda x: x["distance"])[:50]:
        md.append(f"- d={n['distance']} · `{n['left']}`  ↔  `{n['right']}`")
    if not near:
        md.append("_(none)_")

    md += ["", "## Prefix matches",
           "One name is a prefix of the other — could be the same company or a subsidiary.", ""]
    for p in sorted(prefix, key=lambda x: x["shorter"])[:50]:
        md.append(f"- `{p['shorter']}` ⊂ `{p['longer']}`")
    if not prefix:
        md.append("_(none)_")

    md += ["", "## Next step",
           "Manual review with Chris. Mark the truthful canonical name in each cluster, then a",
           "Phase-2 merge script will rewrite Customer references on Quotation, Sales Order, Project,",
           "JWM Production Schedule Line, etc."]

    OUT_MD.write_text("\n".join(md))
    LOG.info("Wrote %s + %s", OUT_MD, OUT_JSON)


if __name__ == "__main__":
    main()
