-- Test Records for FindRawDogFood Database
-- 2 test suppliers: 1 in St Ouens Jersey, 1 in London

-- Test Record 1: Jersey (St Ouens)
INSERT INTO suppliers_complete (
  id,
  place_id,
  name,
  types,
  formatted_address,
  address_components,
  adr_address,
  vicinity,
  postal_code,
  city,
  state,
  country,
  latitude,
  longitude,
  geometry,
  plus_code,
  formatted_phone_number,
  international_phone_number,
  website,
  url,
  business_status,
  opening_hours,
  current_opening_hours,
  secondary_opening_hours,
  utc_offset,
  rating,
  user_ratings_total,
  reviews,
  editorial_summary,
  price_level,
  delivery,
  dine_in,
  takeout,
  reservable,
  curbside_pickup,
  wheelchair_accessible_entrance,
  serves_breakfast,
  serves_lunch,
  serves_dinner,
  serves_brunch,
  serves_beer,
  serves_wine,
  serves_vegetarian_food,
  photos,
  icon,
  icon_mask_base_uri,
  icon_background_color,
  keyword,
  place_type,
  created_at,
  updated_at,
  api_version
) VALUES (
  'test-jersey-001',
  'test_place_id_jersey_001',
  'TEST-JSY',
  '["pet_store", "food", "establishment", "point_of_interest", "store"]',
  'La Route de St Ouens, St Ouens, Jersey JE3 2AB, UK',
  '[{"long_name":"La Route de St Ouens","short_name":"La Route de St Ouens","types":["route"]},{"long_name":"St Ouens","short_name":"St Ouens","types":["locality","political"]},{"long_name":"Jersey","short_name":"Jersey","types":["administrative_area_level_1","political"]},{"long_name":"United Kingdom","short_name":"GB","types":["country","political"]},{"long_name":"JE3 2AB","short_name":"JE3 2AB","types":["postal_code"]}]',
  '<span class="street-address">La Route de St Ouens</span>, <span class="locality">St Ouens</span>, <span class="region">Jersey</span> <span class="postal-code">JE3 2AB</span>, <span class="country-name">UK</span>',
  'St Ouens, Jersey',
  'JE3 2AB',
  'St Ouens',
  'Jersey',
  'United Kingdom',
  49.2247,
  -2.2047,
  '{"location":{"lat":49.2247,"lng":-2.2047},"viewport":{"northeast":{"lat":49.2260483,"lng":-2.2033510},"southwest":{"lat":49.2233517,"lng":-2.2060490}}}',
  '{"global_code":"8CWP6QFW+X7","compound_code":"6QFW+X7 St Ouens, Jersey"}',
  '+44 1534 123456',
  '+44 1534 123456',
  'https://test-jsy-rawfood.je',
  'https://maps.google.com/?cid=12345678901234567890',
  'OPERATIONAL',
  '{"open_now":true,"periods":[{"close":{"day":1,"time":"1700"},"open":{"day":1,"time":"0900"}},{"close":{"day":2,"time":"1700"},"open":{"day":2,"time":"0900"}},{"close":{"day":3,"time":"1700"},"open":{"day":3,"time":"0900"}},{"close":{"day":4,"time":"1700"},"open":{"day":4,"time":"0900"}},{"close":{"day":5,"time":"1700"},"open":{"day":5,"time":"0900"}},{"close":{"day":6,"time":"1600"},"open":{"day":6,"time":"0900"}}],"weekday_text":["Monday: 9:00 AM – 5:00 PM","Tuesday: 9:00 AM – 5:00 PM","Wednesday: 9:00 AM – 5:00 PM","Thursday: 9:00 AM – 5:00 PM","Friday: 9:00 AM – 5:00 PM","Saturday: 9:00 AM – 4:00 PM","Sunday: Closed"]}',
  '{"open_now":true,"periods":[{"close":{"day":1,"time":"1700"},"open":{"day":1,"time":"0900"}},{"close":{"day":2,"time":"1700"},"open":{"day":2,"time":"0900"}},{"close":{"day":3,"time":"1700"},"open":{"day":3,"time":"0900"}},{"close":{"day":4,"time":"1700"},"open":{"day":4,"time":"0900"}},{"close":{"day":5,"time":"1700"},"open":{"day":5,"time":"0900"}},{"close":{"day":6,"time":"1600"},"open":{"day":6,"time":"0900"}}],"weekday_text":["Monday: 9:00 AM – 5:00 PM","Tuesday: 9:00 AM – 5:00 PM","Wednesday: 9:00 AM – 5:00 PM","Thursday: 9:00 AM – 5:00 PM","Friday: 9:00 AM – 5:00 PM","Saturday: 9:00 AM – 4:00 PM","Sunday: Closed"]}',
  null,
  0,
  4.7,
  23,
  '[{"author_name":"Sarah M","author_url":"https://www.google.com/maps/contrib/123456789","language":"en","profile_photo_url":"https://lh3.googleusercontent.com/a/default-user","rating":5,"relative_time_description":"2 months ago","text":"Excellent quality raw dog food! My golden retriever loves their BARF meals. Great local supplier in Jersey.","time":1699123456},{"author_name":"John K","author_url":"https://www.google.com/maps/contrib/987654321","language":"en","profile_photo_url":"https://lh3.googleusercontent.com/a/default-user","rating":4,"relative_time_description":"1 month ago","text":"Good selection of frozen raw food. Helpful staff who know about dog nutrition.","time":1701715456}]',
  'Local raw dog food specialist serving Jersey with premium BARF diets and natural pet nutrition.',
  2,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '[{"height":427,"html_attributions":["<a href=\"https://maps.google.com/maps/contrib/123456789\">TEST-JSY</a>"],"photo_reference":"test_photo_ref_jersey_001","width":640}]',
  'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/shopping-71.png',
  'https://maps.gstatic.com/mapfiles/place_api/icons/v2/shopping_pinlet',
  '#4B96F3',
  'raw dog food',
  'raw_dog_food_complete',
  '2025-07-23T10:00:00.000Z',
  '2025-07-23T10:00:00.000Z',
  'complete_v1.0'
);

-- Test Record 2: London
INSERT INTO suppliers_complete (
  id,
  place_id,
  name,
  types,
  formatted_address,
  address_components,
  adr_address,
  vicinity,
  postal_code,
  city,
  state,
  country,
  latitude,
  longitude,
  geometry,
  plus_code,
  formatted_phone_number,
  international_phone_number,
  website,
  url,
  business_status,
  opening_hours,
  current_opening_hours,
  secondary_opening_hours,
  utc_offset,
  rating,
  user_ratings_total,
  reviews,
  editorial_summary,
  price_level,
  delivery,
  dine_in,
  takeout,
  reservable,
  curbside_pickup,
  wheelchair_accessible_entrance,
  serves_breakfast,
  serves_lunch,
  serves_dinner,
  serves_brunch,
  serves_beer,
  serves_wine,
  serves_vegetarian_food,
  photos,
  icon,
  icon_mask_base_uri,
  icon_background_color,
  keyword,
  place_type,
  created_at,
  updated_at,
  api_version
) VALUES (
  'test-london-001',
  'test_place_id_london_001',
  'TEST-UK',
  '["pet_store", "food", "establishment", "point_of_interest", "store"]',
  '123 Camden High Street, Camden, London NW1 7JR, UK',
  '[{"long_name":"123","short_name":"123","types":["street_number"]},{"long_name":"Camden High Street","short_name":"Camden High St","types":["route"]},{"long_name":"Camden","short_name":"Camden","types":["neighborhood","political"]},{"long_name":"London","short_name":"London","types":["postal_town"]},{"long_name":"Greater London","short_name":"Greater London","types":["administrative_area_level_2","political"]},{"long_name":"England","short_name":"England","types":["administrative_area_level_1","political"]},{"long_name":"United Kingdom","short_name":"GB","types":["country","political"]},{"long_name":"NW1 7JR","short_name":"NW1 7JR","types":["postal_code"]}]',
  '<span class="street-address">123 Camden High Street</span>, <span class="locality">Camden</span>, <span class="region">London</span> <span class="postal-code">NW1 7JR</span>, <span class="country-name">UK</span>',
  'Camden, London',
  'NW1 7JR',
  'London',
  'England',
  'United Kingdom',
  51.5408,
  -0.1426,
  '{"location":{"lat":51.5408,"lng":-0.1426},"viewport":{"northeast":{"lat":51.5421483,"lng":-0.1412510},"southwest":{"lat":51.5394517,"lng":-0.1439490}}}',
  '{"global_code":"9C3XGV84+W7","compound_code":"GV84+W7 Camden, London, UK"}',
  '+44 20 7123 4567',
  '+44 20 7123 4567',
  'https://test-uk-rawpetfood.co.uk',
  'https://maps.google.com/?cid=09876543210987654321',
  'OPERATIONAL',
  '{"open_now":true,"periods":[{"close":{"day":1,"time":"1800"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1800"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1800"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1800"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1800"},"open":{"day":5,"time":"0800"}},{"close":{"day":6,"time":"1700"},"open":{"day":6,"time":"0900"}},{"close":{"day":0,"time":"1600"},"open":{"day":0,"time":"1000"}}],"weekday_text":["Monday: 8:00 AM – 6:00 PM","Tuesday: 8:00 AM – 6:00 PM","Wednesday: 8:00 AM – 6:00 PM","Thursday: 8:00 AM – 6:00 PM","Friday: 8:00 AM – 6:00 PM","Saturday: 9:00 AM – 5:00 PM","Sunday: 10:00 AM – 4:00 PM"]}',
  '{"open_now":true,"periods":[{"close":{"day":1,"time":"1800"},"open":{"day":1,"time":"0800"}},{"close":{"day":2,"time":"1800"},"open":{"day":2,"time":"0800"}},{"close":{"day":3,"time":"1800"},"open":{"day":3,"time":"0800"}},{"close":{"day":4,"time":"1800"},"open":{"day":4,"time":"0800"}},{"close":{"day":5,"time":"1800"},"open":{"day":5,"time":"0800"}},{"close":{"day":6,"time":"1700"},"open":{"day":6,"time":"0900"}},{"close":{"day":0,"time":"1600"},"open":{"day":0,"time":"1000"}}],"weekday_text":["Monday: 8:00 AM – 6:00 PM","Tuesday: 8:00 AM – 6:00 PM","Wednesday: 8:00 AM – 6:00 PM","Thursday: 8:00 AM – 6:00 PM","Friday: 8:00 AM – 6:00 PM","Saturday: 9:00 AM – 5:00 PM","Sunday: 10:00 AM – 4:00 PM"]}',
  null,
  0,
  4.6,
  87,
  '[{"author_name":"Emma L","author_url":"https://www.google.com/maps/contrib/456789123","language":"en","profile_photo_url":"https://lh3.googleusercontent.com/a/default-user","rating":5,"relative_time_description":"3 weeks ago","text":"Fantastic raw dog food store in Camden! They have everything for BARF feeding. Staff are very knowledgeable about raw nutrition.","time":1703123456},{"author_name":"David R","author_url":"https://www.google.com/maps/contrib/789123456","language":"en","profile_photo_url":"https://lh3.googleusercontent.com/a/default-user","rating":4,"relative_time_description":"1 week ago","text":"Great selection of frozen raw meals. My two Labs are thriving on their products. Delivery service is excellent too.","time":1704715456},{"author_name":"Sophie T","author_url":"https://www.google.com/maps/contrib/321654987","language":"en","profile_photo_url":"https://lh3.googleusercontent.com/a/default-user","rating":5,"relative_time_description":"2 days ago","text":"Best raw dog food supplier in London! Premium quality, great prices, and they deliver across Greater London.","time":1705123456}]',
  'Premier raw dog food supplier in Camden, London. Specializing in BARF diets, frozen raw meals, and natural pet nutrition with delivery across Greater London.',
  2,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  '[{"height":480,"html_attributions":["<a href=\"https://maps.google.com/maps/contrib/456789123\">TEST-UK</a>"],"photo_reference":"test_photo_ref_london_001","width":640},{"height":427,"html_attributions":["<a href=\"https://maps.google.com/maps/contrib/789123456\">Customer Photo</a>"],"photo_reference":"test_photo_ref_london_002","width":640}]',
  'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/shopping-71.png',
  'https://maps.gstatic.com/mapfiles/place_api/icons/v2/shopping_pinlet',
  '#4B96F3',
  'raw dog food',
  'raw_dog_food_complete',
  '2025-07-23T10:00:00.000Z',
  '2025-07-23T10:00:00.000Z',
  'complete_v1.0'
);
