apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    basicAuth: false
    jsonData:
      maxLines: 1000
    secureJsonData: {}

  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://node-exporter:9100
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: GET
    secureJsonData: {}