name = "hunta-live-analytics-db"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "hunta-production-secret-2025"

[[d1_databases]]
binding = "DB"
database_name = "hunta-analytics-live"
database_id = "88af67a8-22e5-40a3-9d48-54abc967a47e"