name = "gohunta-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "hunta-production-secret-2025"

# Custom domain routes
routes = [
  { pattern = "api.gohunta.com/*", zone_name = "gohunta.com" },
  { pattern = "gohunta.com/api/*", zone_name = "gohunta.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "hunta-db-prod"
database_id = "8a950a6b-e1c8-4ac0-97bc-ad93c75450b6"

[[kv_namespaces]]
binding = "CACHE"
id = "c53c6240247746f48374f5fc20af1f0c"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "hunta-media-prod"